version: "3.9"

services:
  devmartapp1:
    container_name: devmartapp1
    image: juana/devmartapp1:v1
    build:
      context: .
    ports:
      - "6058:3000"
    networks:
      - devmart-network
    environment:
      HOST: app1servicio

  devmartapp2:
    container_name: devmartapp2
    image: juana/devmartapp1:v1
    build:
      context: .
    ports:
      - "6059:3000"
    networks:
      - devmart-network
    environment:
      HOST: app2servicio

  load_balancer1:
    container_name: nginxsinget
    image: juana/nginxsinget:v1
    build:
      context: src/load-balancer
    ports:
      - "6061:80"
    depends_on:
      - devmartapp1
      - devmartapp2
    networks:
      - devmart-network

networks:
  devmart-network:
    driver: bridge